# src/Application/ShopBundle/Resources/config/doctrine/Product.orm.yml
Application\ShopBundle\Entity\Product:
  type: entity
  #repositoryClass: Application\ShopBundle\Repository\ProductRepository
  table: product
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 100
    description:
      type: string
      length: 255
    description_full:
      type: text
    code:
      type: string
      length: 50
    is_active:
      type: boolean
      nullable: true
      default: 0
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true
  oneToMany:
    reviews:
      targetEntity: Review
      mappedBy: product
      cascade: [ remove ]
  oneToMany:
    images:
      targetEntity: Image
      mappedBy: product
      cascade: [ remove ]
  manyToMany:
    categories:
      targetEntity: Category
      inversedBy: products
      #cascade: [ persist ]
      joinTable:
        name: product_category
        joinColumns:
          product_id:
            referencedColumnName: id
        inverseJoinColumns:
          category_id:
            referencedColumnName: id
  manyToMany:
    orders:
      targetEntity: Order
      inversedBy: products
      #cascade: [ persist ]
      joinTable:
        name: product_order
        joinColumns:
          product_id:
            referencedColumnName: id
        inverseJoinColumns:
          order_id:
            referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ] 
    preUpdate: [ setUpdatedAtValue ]